package org.ciaa.mealplanner.controllers;

import org.ciaa.mealplanner.Control;
import org.ciaa.mealplanner.UserSignIn;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import jakarta.servlet.http.HttpSession;

/**
 * The controller class responsible for handling requests from the log in page
 * of the application, "login.html".
 */
@Controller
public class OldLoginController {

    /**
     * Handles GET requests from "login.html". Responsible for displaying
     * "login.html".
     * 
     * @return the name of the html file to be displayed.
     */
    @GetMapping("/login")
    public String login() {
        return "login";
    }

    /**
     * Handles POST requests from "login.html". If the "Return to Start page" button
     * is pressed, redirects the user to "index.html". Otherwise, checks if the
     * passed UserSignIn object corresponds to a User in the system via
     * Control.checkIfExists(). If the User exists, redirects to "home.html",
     * otherwise "login.html" (this same page).
     * 
     * @param userSignIn       the UserSignIn object automatically generated by the
     *                         "@ModelAttribute" SpringBoot annotation from the data
     *                         form the html form.
     * @param submitFormButton the result of the button press from "login.html".
     * @param session          the HttpSession object created for this UserSignIn.
     * @return the name of the html file to be displayed.
     */
    @PostMapping("/login")
    public String login(@ModelAttribute UserSignIn userSignIn,
            @RequestParam("submitFormButton") String submitFormButton, HttpSession session) {

        // if the 'Return to Start page' button was selected
        if (submitFormButton.equals("start")) {
            return "redirect:/index";
        }
        
        boolean result = Control.authenticateUser(userSignIn);
        if (result) {
            session.setAttribute("firstName", Control.getCurrentUser().getFirstName());
            return "redirect:/home"; // enter the home page
        } else {
            return "redirect:/login"; // reload the login page
        }
    }
}
